website/website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.views.decorators.cache import cache_page

from .views import homepage

urlpatterns = [
    url(r'^$', cache_page(86400)(homepage), name="homepage"),
    url(r'^words/', include('words.urls')),
    url(r'^bureauduchef/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

website/words/urls.py
from django.conf.urls import url
from django.views.decorators.cache import cache_page

from .views import AdvancedSearchView, IndexView, RandomWordView, \
                   SearchQuoteView, SearchView, StatsView, WordView


urlpatterns = [
    url(r'^index$', cache_page(86400)(IndexView.as_view()), name='index'),
    url(r'^stats$', cache_page(86400)(StatsView.as_view()), name='stats'),
    url(r'^random$', RandomWordView.as_view(), name='random'),
    url(r'^advanced_search$', cache_page(86400)(AdvancedSearchView.as_view()), name='advanced_search'),
    url(r'^search$', cache_page(3600)(SearchView.as_view()), name='search'),
    url(r'^searchquote$', cache_page(3600)(SearchQuoteView.as_view()), name='search_quote'),
    url(r'^(?P<title>\w+)$', cache_page(3600)(WordView.as_view()), name='word'),
]

website/words/models.py
from datetime import datetime as dt

import django.utils.timezone
from django.db import models
from django.urls import reverse


class Word(models.Model):
    word = models.CharField(unique=True, max_length=50)
    occurr = models.IntegerField(default=0)
    checked = models.BooleanField(default=False)
    sortkey = models.CharField(max_length=50)
    first = models.DateTimeField(default=django.utils.timezone.now)

    class Meta:
        ordering = ['sortkey']

    def __str__(self):
        return self.word

    def get_absolute_url(self):
        return '/words/' + self.word


class Quote(models.Model):
    quote = models.TextField(unique=True)
    title = models.CharField(max_length=200)
    hour = models.DateTimeField(default=django.utils.timezone.now)
    url = models.URLField(max_length=250)

    class Meta:
        ordering = ['-hour']

    def __str__(self):
        return self.quote

    @property
    def date(self):
        return dt.strftime(self.hour, '%Y-%m-%d')


class Quotes(models.Model):
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    quote = models.ForeignKey(Quote, on_delete=models.CASCADE)

    class Meta:
        ordering = ['quote__hour']
        unique_together = ('word', 'quote')

    def __str__(self):
        return self.quote.quote


class FrenchWords(models.Model):
    word = models.CharField(max_length=100, unique=True)

    class Meta:
        ordering = ['word']

    def __str__(self):
        return self.word


class AnalyzedUrls(models.Model):
    url = models.URLField(unique=True)
    analyzed = models.BooleanField(default=True)
    language = models.CharField(max_length=30, default="french")
    date = models.DateField(default=django.utils.timezone.now)

    def __str__(self):
        return self.url

website/words/forms.py
from django import forms


class AdvancedSearchForm(forms.Form):
    q = forms.CharField(label='Mot', required=False)
    start = forms.CharField(label='Commence par', required=False)
    end = forms.CharField(label='Se termine par', required=False)
    contain = forms.CharField(label='Contient', required=False)


class ExampleSearchForm(forms.Form):
    w = forms.CharField(label='Recherche ', required=False)


QUOTES_SORT_CHOICES = [
    ('rand', 'Aléatoirement'),
    ('desc', 'Du plus ancien au plus récent'),
    ('asc', 'Du plus récent au plus ancien'),
]

PAGE_SIZE = ((size, size) for size in (5, 10, 20, 50))
PERIOD = ((size, size) for size in (1, 3, 7, 14))


class QuotesSortForm(forms.Form):
    quotesort = forms.ChoiceField(choices=QUOTES_SORT_CHOICES,
                                  widget=forms.RadioSelect(),
                                  required=False,
                                  label='Organisation des exemples'
                                  )
    pagesize = forms.MultipleChoiceField(widget=forms.Select,
                                         choices=PAGE_SIZE,
                                         label='Résultats par page')

website/words/views.py
import re
import difflib
import datetime
import unicodedata
from datetime import timedelta
from urllib.parse import urlsplit

from django.urls import reverse
from django.db import connection
from django.utils import timezone
from django.db.models import Q, Count
from django.utils.timezone import now
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic.detail import SingleObjectMixin

from visitors.models import Visitor
from words.utils import get_sortkey
from words.similar import flexions, similar_words
from words.models import Word, Quote, Quotes, AnalyzedUrls
from words.forms import QuotesSortForm, AdvancedSearchForm, ExampleSearchForm


class AdvancedSearchView(FormView):
    template_name = 'words/search_form.html'
    form_class = AdvancedSearchForm
    form_class_ex = ExampleSearchForm

    def get_context_data(self, *args, **kwargs):
        context = super(AdvancedSearchView, self).get_context_data(**kwargs)
        context['searchform'] = self.form_class
        context['searchformex'] = self.form_class_ex
        return context


class IndexView(ListView):
    template_name = 'words/index.html'
    paginate_by = 240

    def get(self, request, *args, **kwargs):
        try:
            self.period = int(request.GET.get('period'))
        except (TypeError, AttributeError):
            self.period = 7
        self.show = request.GET.get('show')
        return super(IndexView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        if not self.show == 'popular':
            return Word.objects.filter(checked=True)
        today = timezone.now()
        start_date = today + datetime.timedelta(days=self.period * -1)
        words_in_range = Quotes.objects.select_related()\
                                       .filter(quote__hour__range=(start_date, today))\
                                       .order_by('word')
        self.queryset = words_in_range.values('word__word')\
                                      .filter(word__checked=True)\
                                      .annotate(count=Count('word'))\
                                      .order_by('-count')
        return self.queryset


class RandomWordView(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        x = Quotes.objects.filter(word__checked=True).order_by('?').first()
        return reverse('word', kwargs={'title': x.word.word})


class SearchView(SingleObjectMixin, ListView):
    model = Word
    template_name = 'words/search.html'
    paginate_by = 60

    def dispatch(self, *args, **kwargs):
        return super(SearchView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        data = request.GET
        if not data:
            raise Http404('No query')
        simple_search = False
        try:
            query = data['q'].lower()
            simple_search = True
        except KeyError:
            pass
        if simple_search:
            try:
                Word.objects.get(word=query, checked=True)
                return HttpResponseRedirect(reverse('word', kwargs={'title': query}))
            except ObjectDoesNotExist:
                pass
            query_sortkey = get_sortkey(query)
            #self.description = ['similaires à <i>' + query + '</i>']
            s = Word.objects.filter(sortkey=query_sortkey, checked=True)
            if len(s) == 1:
                # Unique word matching query_sortkey in database
                return HttpResponseRedirect(reverse('word', kwargs={'title': s.first().word}))
            elif len(s) > 1:
                self.object = s
                self.description = ['très similaires à <i>' + query + '</i>']
            else:
                self.object = []
                all_words = Word.objects.filter(checked=True).values_list('word', flat=True)
                suggested_words = difflib.get_close_matches(query, all_words, n=100)
                for w in suggested_words:
                    self.object.append(Word.objects.get(word=w))
                if len(self.object) == 1:
                    self.description = ['similaire à <i>' + query + '</i>']
                else:
                    self.description = ['similaires à <i>' + query + '</i>']

        else:
            self.description = []
            start = get_sortkey(data['start'])
            end = get_sortkey(data['end'])
            contain = get_sortkey(data['contain'])
            self.object = Word.objects.filter(sortkey__startswith=start)\
                                      .filter(sortkey__endswith=end)\
                                      .filter(sortkey__contains=contain)
            if start:
                if len(self.object) == 1:
                    self.description.append('commençant par <i>' + data['start'] + '</i>')
                else:
                    self.description.append('commençants par <i>' + data['start'] + '</i>')
            if end:
                if len(self.object) == 1:
                    self.description.append('finissant par <i>' + data['end'] + '</i>')
                else:
                    self.description.append('finissants par <i>' + data['end'] + '</i>')
            if contain:
                if len(self.object) == 1:
                    self.description.append('contenant <i>' + data['contain'] + '</i>')
                else:
                    self.description.append('contenants <i>' + data['contain'] + '</i>')
        self.data = data
        return super(SearchView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['suggested_words'] = self.object
        context['description'] = self.description
        context['queries'] = self.data
        return context

    def get_queryset(self):
        return self.object

    def get_paginate_by(self, queryset):
        """
        User can customize the number of results per page (paginate_by) in
        the URL between 5 and 500.
        """
        try:
            pagesize = int(self.request.GET.get('paginateby'))
        except (ValueError, TypeError):
            pagesize = self.paginate_by
        if 4 > pagesize < 501:
            pagesize = self.paginate_by
        return pagesize


class SearchQuoteView(ListView):
    """View to search string among examples."""
    model = Quote
    paginate_by = 10
    template_name = "words/search_quote.html"

    def _normalize_query(self, query_string):
        findterms = re.compile(r'"([^"]+)"|(\S+)').findall
        normspace = re.compile(r'\s{2,}').sub
        return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

    def _get_query(self, query_string):
        query = None
        terms = self._normalize_query(query_string)
        for term in terms:
            query = Q(**{"quotes__quote__quote__icontains": term, "quotes__word__checked": True})
        return query

    def get(self, request, *args, **kwargs):
        if not request.GET.get('w'):
            raise Http404('No query')
        self.query_string = request.GET.get('w')
        self.entry_query = self._get_query(self.query_string)
        return super(SearchQuoteView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return Quote.objects.filter(self.entry_query)


    def get_context_data(self, **kwargs):
        context = super(SearchQuoteView, self).get_context_data(**kwargs)
        context['query'] = self.query_string
        return context


class StatsView(ListView):
    template_name = "words/stats.html"
    queryset = Word  # Useless but required

    def get(self, request, *args, **kwargs):
        today = timezone.now()
        period = 7  # Period by default
        if request.GET.get('period'):
            period = int(request.GET.get('period'))
        start_date = today + datetime.timedelta(days=period * -1)
        words_in_range = Quotes.objects.select_related()\
                                       .filter(word__checked=True)\
                                       .filter(quote__hour__range=(start_date, today))\
                                       .order_by('quote__hour')
        self.popular_words = words_in_range.values('word__word')\
                                           .filter(word__checked=True)\
                                           .annotate(count = Count('word__word'))\
                                           .order_by('-count')[:30]
        self.last_words = Word.objects.filter(checked=True).order_by('-first')[:36]
        self.analyzed_urls = self._quick_urls_count('words_analyzedurls')
        return super(StatsView, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(StatsView, self).get_context_data(**kwargs)
        context['words'] = Word.objects.filter(checked=True).count()
        context['quotes'] = Quotes.objects.filter(word__checked=True).count()
        context['websites'] = self._websites_nb()
        context['popular_words'] = self.popular_words
        context['last_new_words'] = self.last_words
        context['unique_visitors'] = Visitor.objects.count()
        context['analyzed_urls'] = self.analyzed_urls
        return context

    def _websites_nb(self):
        websites = set()
        for x in Quote.objects.all():
            websites.add(urlsplit(x.url).netloc)
        return len(websites)

    def _quick_urls_count(self, table):
        """Quick (approximately) count of analyzed urls."""
        with connection.cursor() as cursor:
            cursor.execute(f"""SELECT reltuples FROM pg_class WHERE relname = '{table}';""")

website/templates/words/index.html
{% extends "base.html" %}
{% load bootstrap_pagination %}

{% block title %}Index - {% endblock %}

{% block content %}
<div class="container">
<div class="page-header">
  <h1>Index</h1>
</div>

<div class="content-index">
  <table>
    <ul>
      {% if word_list %}
        {% for word in word_list %}
        <span class="badge">{{word.occurr}}</span> <a href="{{word.get_absolute_url}}">{{ word.word }}</a><br>
        {% endfor %}
      {% else %}
        {% for word in object_list %}
        <span class="badge">{{word.count}}</span> <a href={% url 'word' title=word.word__word %}>{{word.word__word}}</a><br>
        {% endfor %}
      {% endif %}
    </ul>
  </table>
</div>

<div class="tablePagination">
  {% bootstrap_paginate page_obj range=10 previous_label="Précédent" next_label="Suivant" show_first_last="true" %}
</div>
</div>

{% endblock %}

website/templates/words/search.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap_pagination %}

{% block title %}Recherche - {% endblock %}

{% block content %}
<div class="container">
  <div class="search_results">
    {% if not suggested_words %}
      <h3>Il n’y a aucun résultat correspondant à la requête.</h3>
    {% endif %}
    {% if suggested_words %}
      <h3 style="margin-left:50px;">{% include "includes/descr.html" %}</h3>
      <div class="suggested_words"  style="column-width: 220px; margin-top:50px;">
      {% for x in object_list %}
        <span class="badge">{{x.occurr}}</span> <a href="{{x.get_absolute_url}}">{{ x.word }}</a><br>
      {% endfor %}
      </div>
    {% endif %}
  </div>

  {% if page_obj.has_next or page_obj.has_previous %}
  <div class="tablePagination">
    {% bootstrap_paginate page_obj range=10 previous_label="Précédent" next_label="Suivant" show_first_last="true" %}
  </div>
  {% endif %}
</div>
{% endblock %}

website/templates/words/search_form.html
{% extends "base.html" %}
{% load static %}


{% block title %}Recherche Avancée - {% endblock %}

{% block content %}

<script type="text/javascript" src={% static "js/advanced_research.js" %}></script>
<div class="container">

  <div class="page-header">
    <h1>Recherche Avancée</h1>
  </div>
  <div class="col-md-6">
    <form class="search-tool" action="search" method="get" style="max-width:400px; margin-top:40px;">
      <h3 style="text-align:center;">Rechercher un mot</h3>
      <div class="search-form">
        {{ searchform.as_p}}
      </div>
      <input type="submit" value="Rechercher un mot" />
    </form>
  </div>
  <div class="col-md-6">
    <form class="search-tool" action="searchquote" method="get">
      <h3 style="text-align:center;">Rechercher un exemple</h3>
      <div class="search-form">
        {{ searchformex.as_p}}
      </div>
      <input type="submit" value="Rechercher un exemple">
    </form>
  </div>
</div>
{% endblock %}

website/templates/words/search_quote.html
{% extends "base.html" %}
{% load my_filters %}
{% load static %}
{% load bootstrap_pagination %}

{% block title %}Recherche - {% endblock %}

{% block content %}
<div class="container">
  <div class="search_results">
    {% if not object_list %}
      <h3>Il n’y a aucun résultat correspondant à la requête.</h3>
    {% endif %}
    {% if object_list %}
      <h3 style="margin-left:50px;">Résultat{{object_list|pluralize}} pour votre requête</h3>
      <div class="content-quotes">
      {% for w in object_list %}
      <div class="well" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop=citation>
          {% autoescape off %}
            {% with quote=w.quote|bold_query:query %}
            {{ quote|quote_links:w.id }}
            {% endwith %}
          {% endautoescape %}
        </span>
        <p style="padding-top: 5px;"><small><a href={{ w.url }}> {{ w.title }}</a>, sur <i>{{ w.url|clean_site }}</i> le {{ w.hour|date:"d F Y" }}.</small></p>
      </div>
      {% endfor %}
      </div>
    {% endif %}
  </div>

  {% if page_obj.has_next or page_obj.has_previous %}
  <div class="tablePagination">
    {% bootstrap_paginate page_obj range=10 previous_label="Précédent" next_label="Suivant" show_first_last="true" %}
  </div>
  {% endif %}
</div>
{% endblock %}

website/templates/words/stats.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}Statistiques - {% endblock %}

{% block content %}
<script type="text/javascript">
function sdf_FTS(_number,_decimal,_separator)
{
var decimal=(typeof(_decimal)!='undefined')?_decimal:2;
var separator=(typeof(_separator)!='undefined')?_separator:'';
var r=parseFloat(_number)
var exp10=Math.pow(10,decimal);
r=Math.round(r*exp10)/exp10;
rr=Number(r).toFixed(decimal).toString().split('.');
b=rr[0].replace(/(\d{1,3}(?=(\d{3})+(?:\.\d|\b)))/g,"\$1"+separator);
r=(rr[1]?b+'.'+rr[1]:b);

return r;
}

setTimeout(function(){
  $('#counter').text('0');
  $('#counter1').text('0');
  $('#counter2').text('0');
  setInterval(function(){

    var curval=parseInt($('#counter').text().replace(' ',''));
    var curval1=parseInt($('#counter1').text().replace(' ',''));
    var curval2=parseInt($('#counter2').text());
    if(curval<{{words}}){
      $('#counter').text(sdf_FTS((curval+20),0,' '));
    } else {
      $('#counter').text(sdf_FTS({{words}},0,' '));
    }
    if(curval1<{{quotes}}){
      $('#counter1').text(sdf_FTS((curval1+50),0,' '));
    } else {
      $('#counter1').text(sdf_FTS({{quotes}},0,' '));
    }
    if(curval2<{{websites}}){
      $('#counter2').text(sdf_FTS((curval2+1),0,' '));
    } else {
      $('#counter2').text(sdf_FTS({{websites}},0,' '));
    }
  }, 2);

}, 500);
</script>
<script type="text/javascript" src={% static "js/stats.js" %}></script>
<div class="container">
  <div class="page-header">
    <h1>Statistiques</h1>
  </div>
  <div class="row">
    <div class="col-md-4 project">
      <div class="col-md-12 well new-words" style="background-color:#CDECE7;">
        <h3 id="counter" value="{{words}}">0</h3>
        <h4>Nouveaux Mots</h4>
      </div>
    </div>
    <div class="col-md-4 project">
      <div class="col-md-12 well examples" style="background-color:#8db7db;">
        <h3 id="counter1" value="{{quotes}}">0</h3>
        <h4>Exemples</h4>
      </div>
    </div>
    <div class="col-md-4 project">
      <div class="col-md-12 well websites" style="background-color:#CEE1FB;">
        <h3 id="counter2" value="{{websites}}">0</h3>
        <h4>Sites Internet</h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 project">
      <div class="col-md-12 well urls" style="background-color:#A5CBCF;">
        <h3>{{ unique_visitors|intcomma }}</h3>
        <h4>Visiteurs uniques</h4>
      </div>
    </div>
    <div class="col-md-6 project">
      <div class="col-md-12 well visitors" style="background-color:#F7C9C9;">
        <h3>{{ analyzed_urls|intcomma }}</h3>
        <h4>Pages web analysées</h4>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="class-md-12 well" style="background-color:#dcf1ee">
        <h3 style="text-align:center;">Néologismes populaires</h3>
        <p class="text-center">
          <select class="popular-period text-center" id="selectPeriod">
            <option value="7" selected="selected">7 derniers jours</option>
            <option value="14">14 derniers jours</option>
            <option value="28">28 derniers jours</option>
          </select>
        </p>
        <div class="stats popular-words">
        {% for word in popular_words %}
          <span class="badge">{{word.count}}</span> <a href="{{word.word__word}}">{{ word.word__word }}</a><br>
        {% endfor %}
        </div>
        <p class="text-right"><br><a href="/words/index?show=popular" id="seeMore">Voir plus <i class="fa fa-chevron-right" aria-hidden="true" style="vertical-align: middle;"></i></a></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="class-md-12 well" style="background-color:#b0cde2">
        <h3 style="text-align:center;">Derniers mots apparus</h3>
        <div class="stats latest-words" style="margin-bottom:32px;">
          {% for word in last_new_words %}
            <span class="badge">{{word.occurr}}</span> <a href="{{word.word}}">{{ word.word }}</a><br>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/words/word.html
{% extends "base.html" %}
{% load my_filters %}
{% load static %}
{% load bootstrap_pagination %}

{% block title %}{{title|title}} - {% endblock %}

      {% block content %}

      <script type="text/javascript" src={% static "js/word.js" %}></script>

      <div class="container">
        <div class="page-header">
          <h1>{{title|title}}</h1>
        </div>
      {% if similar or flexions %}<div class="col-md-9">{% else %}<div class="col-md-12">{% endif %}
      <div class="parameters">
        <div id="box" class="box-param">
          <span id="box-title">Paramètres avancés</span>
          <span id="box-view" style="cursor: pointer">Enrouler ▲</span>
        </div>
        <div id="advanced-param" class="adv-param">
          <form class="word_form" action="{{request.url}}" method="get">
            {{quotesform.as_p}}
            <input type="submit" value="Trier" />
          </form>
        </div>
      </div>

      <div class="content-quotes">
        {% for w in object_list %}
        <div class="well" itemscope="" itemtype="http://schema.org/CreativeWork">
          <span class="text" itemprop=citation>
            {% autoescape off %}
              {{ w.quote.quote|quote_decorator:w.id }}
            {% endautoescape %}
          </span>
          <p style="padding-top: 5px;"><small><a href={{ w.quote.url }}> {{ w.quote.title }}</a>, sur <i>{{ w.quote.url|clean_site }}</i> le {{ w.quote.hour|date:"d F Y" }}.</small></p>
        </div>
        {% endfor %}
      </div>
      <div class="example-count text-right" {% if page_obj.has_next or page_obj.has_previous %}style="color:red;"{% else %}style="color:red;margin-bottom:50px;"{% endif %}>
        <p>{{word|length}} exemple{{word|pluralize}}</p>
      </div>

      {% if page_obj.has_next or page_obj.has_previous %}
      <div class="tablePagination">
        {% bootstrap_paginate page_obj range=10 previous_label="Précédent" next_label="Suivant" show_first_last="true" url_param_view="sort={{ key }}&page=" %}
      </div>
      {% endif %}
      </div>


      {% if flexions or similar %}
      <div class="col-md-3">
      <div class="alt-words text-center">
        {% if flexions %}
        <h4 style="padding:10px;">Flexion{{flexions|pluralize}}</h4>
        <div class="btn-group text-justify" style="margin-bottom:30px;">
        {% for f in flexions %}
          <a href="{{f.get_absolute_url}}"><button type="button" class="btn btn-primary"><span class="badge">{{f.occurr}}</span> {{f.word}}</button></a><br>
        {% endfor %}
        </div>
        {% endif %}
        {% if similar %}
        <h4 style="padding:10px;">Similaire{{similar|pluralize}}</h4>
        <div class="btn-group text-justify" style="margin-bottom:30px;">
        {% for s in similar %}
          <a href="{{s.get_absolute_url}}"><button type="button" class="btn btn-primary"><span class="badge">{{s.occurr}}</span> {{s.word}}</button></a><br>
        {% endfor %}
        </div>
        {% endif %}
      </div>
      </div>
      {% endif %}
      </div>
      {% endblock %}